### ISSUE TITLE
PROBLEMS ESTIMATING PANEL DATA

### ISSUE THREAD

**Issue by bpinto2** [HungJenWang1991/SFrontiers.jl#5]
Hi! 

I had no problems using a cross-sectional model. But when I try to use the panel model, it says that "The `sfpanel()` and/or `sfdist()` are not specified correctly."

var"#sfmodel_spec#43"(::Bool, ::typeof(SFrontiers.sfmodel_spec), ::Tuple{Symbol, Vector{Symbol}}, ::Vararg{Tuple{Symbol, Vector{Symbol}}})@SFmainfun.jl:212
sfmodel_spec@SFmainfun.jl:99[inlined]
top-level scope@[Local: 1](http://localhost:1234/edit?id=254cfa70-9062-11ed-3167-eb519d90c004#)[inlined]

Everything seems correct in terms of coding. It seems that there is a problem with the sfpanel code, because the cross-sectional works just fine. 

I am a beginner in Julia, so I may be missing an easy solution here. 

This is my code: 
sfmodel_spec(sfpanel(TFE_WH2010), sftype(prod),  sfdist(trun),
             @timevar(year), @idvar(fips),
             @depvar(lprod), 
             @frontier(lfertilizer_index1, lchemical_index1), 
             @μ(_cons),
             @hscale(precip),                # h(.) function
             @σᵤ²(_cons),
             @σᵥ²(_cons))

Thanks in advance!

**Comment by HJW019** [comment]
Unbalanced panel data is not a problem. I noticed that you had `@IdVar(...)` ; the macro should be in lower cases as `@idvar(...)`.  Please see if the correction would fix the problem.

**Comment by bpinto2** [comment]
I just ran with the correct name and it is still not working. I had the same problem as before. 

"The `sfpanel()` and/or `sfdist()` are not specified correctly."

var"#sfmodel_spec#43"(::Bool, ::typeof(SFrontiers.sfmodel_spec), ::Tuple{Symbol, Vector{Symbol}}, ::Vararg{Tuple{Symbol, Vector{Symbol}}})@SFmainfun.jl:212
sfmodel_spec@SFmainfun.jl:99[inlined]
top-level scope@[Local: 1](http://localhost:1234/edit?id=254cfa70-9062-11ed-3167-eb519d90c004#)[inlined]

Code: 
sfmodel_spec(sfpanel(TFE_WH2010), sftype(prod), sfdist(trun),
             @timevar(year), @idvar(fips),
             @depvar(lprod), 
             @frontier(lfertilizer_index1, lchemical_index1), 
             @μ(_cons),
             @hscale(precip, precip2),                # h(.) function
             @σᵤ²(_cons),
             @σᵥ²(_cons))

**Comment by bpinto2** [comment]
I corrected the name and still had the same problem. 

"The `sfpanel()` and/or `sfdist()` are not specified correctly."

var"#sfmodel_spec#43"(::Bool, ::typeof(SFrontiers.sfmodel_spec), ::Tuple{Symbol, Vector{Symbol}}, ::Vararg{Tuple{Symbol, Vector{Symbol}}})@SFmainfun.jl:212
top-level scope@[Local: 1](http://localhost:1234/edit?id=254cfa70-9062-11ed-3167-eb519d90c004#)[inlined]

code:
sfmodel_spec(sfpanel(TFE_WH2010), sftype(prod), sfdist(trun),
             @timevar(year), @idvar(fips),
             @depvar(lprod), 
             @frontier(lfertilizer_index1, lchemical_index1), 
             @μ(_cons),
             @hscale(precip, precip2),                # h(.) function
             @σᵤ²(_cons),
             @σᵥ²(_cons), message= true)

**Comment by bpinto2** [comment]
I corrected the name and still had the same problem.

"The sfpanel() and/or sfdist() are not specified correctly."

var"#sfmodel_spec#43"(::Bool, ::typeof(SFrontiers.sfmodel_spec), ::Tuple{Symbol, Vector{Symbol}}, ::Vararg{Tuple{Symbol, Vector{Symbol}}})@SFmainfun.jl:212
top-level scope@[Local: 1](http://localhost:1234/edit?id=254cfa70-9062-11ed-3167-eb519d90c004#)[inlined]


code: 

`sfmodel_spec(sfpanel(TFE_WH2010), sftype(prod), sfdist(trun),
             @timevar(year), @idvar(fips),
             @depvar(lprod), 
             @frontier(lfertilizer_index1, lchemical_index1), 
             @μ(_cons),
             @hscale(precip, precip2),                # h(.) function
             @σᵤ²(_cons),
             @σᵥ²(_cons), message= true)`

**Comment by HJW019** [comment]
[WH2010T.csv](https://github.com/HungJenWang1991/SFrontiers.jl/files/10393814/WH2010T.csv)

I couldn't reproduce the problem. Please use the attached dataset (WH2010T.csv) and run the following code and let me know if problems still occur. I have no problem running it with Julia 1.8.3 in Windows. Which version of Julia are you using and in which plateform (Windows, Mac, or Linux)?


``` 
df = DataFrame(CSV.File("WH2010T.csv")) 

df[!, :_cons] .= 1.0


sfmodel_spec( sfpanel(TFE_WH2010), sftype(prod), sfdist(trun),
              @timevar(time), @idvar(id),
              @depvar(yit), 
              @frontier(xit), 
              @μ(_cons),
              @hscale(zit),
              @σᵤ²(_cons),
              @σᵥ²(_cons))
              
sfmodel_init()


sfmodel_opt( warmstart_solver(NelderMead()),  
             warmstart_maxIT(200),
             main_solver(Newton()), 
             main_maxIT(2000), 
             tolerance(1e-8))

res = ()

res = sfmodel_fit(useData(df))              
```

**Comment by bpinto2** [comment]
Sorry for the late response. I opted to work in Stata and R. Thank you for helping me!
